### ISSUE TITLE
Formatting of timestamp in logger WriteSink

### ISSUE THREAD

**Issue by priteshgudge** [coreos/go-log#11]
I am using the following writesink format:
```
loggerObj = log.New("orderhold", false,
			log.WriterSink(os.Stderr,
				"%v [%d]:%s %s\n",
				[]string{"start_time", "pid", "priority", "message"}))

```
The following is the output:
```

2018-03-02 20:00:40.142445373 +0530 IST m=+0.003045469 [23124]:INFO Setting up resources.
2018-03-02 20:00:40.142445373 +0530 IST m=+0.003045469 [23124]:INFO Resource Setup Done.

```
The writesink params only accept list of strings. How do I format timestamp for out put to be:
```

2018-03-02 20:00:40.142445373 +0530 IST [23124]:INFO Setting up resources.
2018-03-02 20:00:40.142445373 +0530 IST [23124]:INFO Resource Setup Done.

```

**Comment by lucab** [comment]
@priteshgudge Thanks for the report. Unfortunately we are not actively developing this package anymore. If you are starting a new project or using this in some other software, and hitting some limitation/bug, I highly recommend you to look into other more active logging framework.

**Comment by priteshgudge** [comment]
Thanks. I will look into it.

**Comment by lucab** [comment]
I forgot to explicitly mention them, but nowadays typical choices are https://github.com/sirupsen/logrus and https://github.com/golang/glog.
